import { OrderType } from "@/type/orderTypes";
import { initialPayments } from "./paymentDb";
import { initialProducts } from "./productDb";

export const initialOrders: OrderType[] = [
  {
    id: "ORD001",
    orderNumber: "110724ORD001",
    status: "Shipped",
    qty: 3,
    total: 109.97,
    customerId: "D4e5F6",
    paymentId: "PYM001",
    paymentStatus: "Completed",
    payment: initialPayments.find((payment) => payment.id === "PYM001"),
    items: [
      {
        id: "I0001",
        productId: "P001",
        quantity: 1,
        price: 29.99,
        product: initialProducts.find((product) => product.id === "P001"),
      },
      {
        id: "I0002",
        productId: "P004",
        quantity: 2,
        price: 79.98,
        product: initialProducts.find((product) => product.id === "P004"),
      },
    ],
    orderDate: "01-06-2024",
  },
  {
    id: "ORD002",
    orderNumber: "110724ORD002",
    status: "Processing",
    qty: 2,
    total: 199.98,
    customerId: "D4e5F6",
    paymentId: "PYM002",
    paymentStatus: "Pending",
    payment: initialPayments.find((payment) => payment.id === "PYM002"),
    items: [
      {
        id: "I0003",
        productId: "P002",
        quantity: 2,
        price: 199.98,
        product: initialProducts.find((product) => product.id === "P002"),
      },
    ],
    orderDate: "02-06-2024",
  },
  {
    id: "ORD003",
    orderNumber: "110724ORD003",
    status: "Delivered",
    qty: 1,
    total: 49.99,
    customerId: "D4e5F6",
    paymentId: "PYM001",
    paymentStatus: "Completed",
    payment: initialPayments.find((payment) => payment.id === "PYM001"),
    items: [
      {
        id: "I0004",
        productId: "P006",
        quantity: 1,
        price: 49.99,
        product: initialProducts.find((product) => product.id === "P006"),
      },
    ],
    orderDate: "03-06-2024",
  },
  {
    id: "ORD004",
    orderNumber: "110724ORD004",
    status: "Cancelled",
    qty: 4,
    total: 239.96,
    customerId: "D4e5F6",
    paymentId: "PYM002",
    paymentStatus: "Refunded",
    payment: initialPayments.find((payment) => payment.id === "PYM002"),
    items: [
      {
        id: "I0005",
        productId: "P007",
        quantity: 4,
        price: 239.96,
        product: initialProducts.find((product) => product.id === "P007"),
      },
    ],
    orderDate: "04-06-2024",
  },
  {
    id: "ORD005",
    orderNumber: "110724ORD005",
    status: "Shipped",
    qty: 2,
    total: 59.98,
    customerId: "D4e5F6",
    paymentId: "PYM001",
    paymentStatus: "Completed",
    payment: initialPayments.find((payment) => payment.id === "PYM001"),
    items: [
      {
        id: "I0006",
        productId: "P008",
        quantity: 2,
        price: 59.98,
        product: initialProducts.find((product) => product.id === "P008"),
      },
    ],
    orderDate: "05-06-2024",
  },
  {
    id: "ORD006",
    orderNumber: "110724ORD006",
    status: "Processing",
    qty: 1,
    total: 14.99,
    customerId: "D4e5F6",
    paymentId: "PYM002",
    paymentStatus: "Pending",
    payment: initialPayments.find((payment) => payment.id === "PYM002"),
    items: [
      {
        id: "I0007",
        productId: "P009",
        quantity: 1,
        price: 14.99,
        product: initialProducts.find((product) => product.id === "P009"),
      },
    ],
    orderDate: "06-06-2024",
  },
  {
    id: "ORD007",
    orderNumber: "110724ORD007",
    status: "Delivered",
    qty: 3,
    total: 104.97,
    customerId: "D4e5F6",
    paymentId: "PYM002",
    paymentStatus: "Completed",
    payment: initialPayments.find((payment) => payment.id === "PYM002"),
    items: [
      {
        id: "I0008",
        productId: "P010",
        quantity: 3,
        price: 104.97,
        product: initialProducts.find((product) => product.id === "P010"),
      },
    ],
    orderDate: "07-06-2024",
  },
  {
    id: "ORD008",
    orderNumber: "110724ORD008",
    status: "Shipped",
    qty: 1,
    total: 34.99,
    customerId: "Stu901",
    paymentId: "PYM001",
    paymentStatus: "Completed",
    payment: initialPayments.find((payment) => payment.id === "PYM001"),
    items: [
      {
        id: "I0009",
        productId: "P010",
        quantity: 1,
        price: 34.99,
        product: initialProducts.find((product) => product.id === "P010"),
      },
    ],
    orderDate: "08-06-2024",
  },
  {
    id: "ORD009",
    orderNumber: "110724ORD009",
    status: "Processing",
    qty: 2,
    total: 119.98,
    customerId: "Vwx234",
    paymentId: "PYM001",
    paymentStatus: "Pending",
    payment: initialPayments.find((payment) => payment.id === "PYM001"),
    items: [
      {
        id: "I0010",
        productId: "P002",
        quantity: 2,
        price: 119.98,
        product: initialProducts.find((product) => product.id === "P002"),
      },
    ],
    orderDate: "09-06-2024",
  },
  {
    id: "ORD010",
    orderNumber: "110724ORD010",
    status: "Delivered",
    qty: 1,
    total: 79.99,
    customerId: "Yza567",
    paymentId: "PYM001",
    paymentStatus: "Completed",
    payment: initialPayments.find((payment) => payment.id === "PYM001"),
    items: [
      {
        id: "I0011",
        productId: "P004",
        quantity: 1,
        price: 79.99,
        product: initialProducts.find((product) => product.id === "P004"),
      },
    ],
    orderDate: "10-06-2024",
  },
];
