import { ProductType } from "@type/productTypes";
import { initialCategories } from "./categoryDb";

export const initialProducts: ProductType[] = [
  {
    id: "P001",
    name: "Wireless Mouse",
    categoryId: "C001",
    price: 29.99,
    code: "WM001",
    isActive: true,
    imageUrl: "/assets/img/products/wireless-mouse.png",
    category: initialCategories.find((category) => category.id === "C001")!,
  },
  {
    id: "P002",
    name: "Bluetooth Headphones",
    categoryId: "C001",
    price: 99.99,
    code: "BH002",
    isActive: true,
    imageUrl: "/assets/img/products/bluetooth-headphones.png",
    category: initialCategories.find((category) => category.id === "C001")!,
  },
  {
    id: "P003",
    name: "Smartphone Stand",
    categoryId: "C003",
    price: 19.99,
    code: "SS003",
    isActive: true,
    imageUrl: "/assets/img/products/smartphone-stand.png",
    category: initialCategories.find((category) => category.id === "C003")!,
  },
  {
    id: "P004",
    name: "Gaming Keyboard",
    categoryId: "C001",
    price: 79.99,
    code: "GK004",
    isActive: false,
    imageUrl: "/assets/img/products/gaming-keyboard.png",
    category: initialCategories.find((category) => category.id === "C001")!,
  },
  {
    id: "P005",
    name: "Portable Charger",
    categoryId: "C001",
    price: 39.99,
    code: "PC005",
    isActive: false,
    imageUrl: "/assets/img/products/portable-charger.png",
    category: initialCategories.find((category) => category.id === "C001")!,
  },
  {
    id: "P006",
    name: "LED Desk Lamp",
    categoryId: "C003",
    price: 49.99,
    code: "LD006",
    isActive: true,
    imageUrl: "/assets/img/products/led-desk-lamp.png",
    category: initialCategories.find((category) => category.id === "C003")!,
  },
  {
    id: "P007",
    name: "Running Shoes",
    categoryId: "C005",
    price: 59.99,
    code: "RS007",
    isActive: true,
    imageUrl: "/assets/img/products/running-shoes.png",
    category: initialCategories.find((category) => category.id === "C005")!,
  },
  {
    id: "P008",
    name: "Yoga Mat",
    categoryId: "C005",
    price: 25.99,
    code: "YM008",
    isActive: true,
    imageUrl: "/assets/img/products/yoga-mat.png",
    category: initialCategories.find((category) => category.id === "C005")!,
  },
  {
    id: "P009",
    name: "Fiction Book",
    categoryId: "C004",
    price: 14.99,
    code: "FB009",
    isActive: true,
    imageUrl: "/assets/img/products/fiction-book.png",
    category: initialCategories.find((category) => category.id === "C004")!,
  },
  {
    id: "P010",
    name: "Electric Toothbrush",
    categoryId: "C007",
    price: 34.99,
    code: "ET010",
    isActive: true,
    imageUrl: "/assets/img/products/electric-toothbrush.png",
    category: initialCategories.find((category) => category.id === "C007")!,
  },
];
